version: 2.1

executors:
  docker:
    docker:
      - image: circleci/golang:1.16.12

commands: # a reusable command with parameters
  create-github-release:
    description: Create Github Release or Pre-Release
    parameters:
      ghr-option:
        default: ""
        type: string
    steps:
      - run: |
          go get github.com/cxflowtestuser/ghr
          VERSION=$(cat ./build/libs/version.txt)
          rm ./build/libs/version.txt
          mv build/libs/java11/repo-${VERSION}.jar build/libs/cx-flow-${VERSION}-java11.jar
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -n ${VERSION} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} << parameters.ghr-option >> -delete ${VERSION} ./build/libs/
jobs:
  publish-github-pre-release:
    docker:
      - image: circleci/golang:1.16.12
    steps:
      - attach_workspace:
          at: .
      - create-github-release:
          ghr-option: "-prerelease "

workflows:
  version: 2

  build_deploy:
    jobs:
      - publish-github-pre-release:
          filters:
            branches:
              only: main
